image: node:12.13.0-alpine
stages:
  - test
  - publish
before_script:
  - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
  - if [ "$(npm view $(npm run --silent getName) version)" != "$(npm run --silent getVersion)" ]; then npm publish --verbose; fi
cache:
  key: one-key-to-rule-them-all

test_smoke:
  stage: test
  script:
    - npm install
    - npm run test:smoke
  when: on_success

publish_production:
  stage: publish
  script:
    - npm dist-tag add $(npm run --silent getNameAndVersion) production
  environment:
    name: production
    url: https://www.npmjs.com/package/@davidhunting/mongoschemas
  when: on_success
  only:
    refs:
      - master

publish_development:
  stage: publish
  script:
    - npm dist-tag add $(npm run --silent getNameAndVersion) development
  environment:
    name: development
    url: https://www.npmjs.com/package/@davidhunting/mongoschemas
  when: on_success
  only:
    refs:
      - development

publish_all:
  stage: publish
  script:
    - npm dist-tag add $(npm run --silent getNameAndVersion) ${CI_COMMIT_REF_NAME}
  environment:
    name: default
    url: https://www.npmjs.com/package/@davidhunting/mongoschemas
  when: on_success
  except:
    refs:
      - master
      - development
